json:
  date:
    key: date_holiday
    type: date
  localName:
    key: local_name
    type: string
  name:
    key: name_holiday
    type: string
  countryCode:
    key: country_code
    type: string
  fixed:
    key: fixed
    type: boolean
  global:
    key: global
    type: boolean
  counties:
    key: title
    type: array
  launchYear:
    key: launch_year
    type: int
  type:
    key: type_holiday
    type: string
